# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts__E4Gu7Sr2QpOtlEa6gGSyzmf8QY6x
"""

"""
UPI DASHBOARD 2016-2025
Professional Financial Analytics Platform
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
from datetime import datetime

# ============================================================================
# PAGE CONFIGURATION
# ============================================================================
st.set_page_config(
    page_title="UPI Analytics Platform 2016-2025",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# UPI Brand Colors - Professional Theme
UPI_COLORS = {
    "primary": "#FF9933",      # Saffron Orange
    "secondary": "#138808",    # India Green
    "dark": "#1A1A1A",         # Dark for text
    "light": "#F5F5F5",        # Light background
    "success": "#138808",
    "warning": "#FF9933",
    "info": "#2E86AB",
    "border": "#E0E0E0",
    "card_bg": "#FFFFFF",
    "text_primary": "#1A1A1A",
    "text_secondary": "#666666"
}

# Custom CSS for Professional Theme
st.markdown("""
<style>
    /* Main container */
    .main {
        background-color: #F8F9FA;
    }

    /* Headers */
    h1, h2, h3, h4, h5, h6 {
        color: #1A1A1A !important;
        font-family: 'Inter', 'Segoe UI', sans-serif;
        font-weight: 600;
    }

    /* Professional Cards */
    .professional-card {
        background: #FFFFFF;
        border-radius: 12px;
        padding: 1.5rem;
        box-shadow: 0 2px 8px rgba(0,0,0,0.04);
        border: 1px solid #E8E8E8;
        transition: all 0.2s ease;
    }

    .professional-card:hover {
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        border-color: #FF9933;
    }

    /* Metric Container */
    .metric-container {
        background: #FFFFFF;
        border-radius: 12px;
        padding: 1.25rem;
        border-left: 4px solid #FF9933;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }

    .metric-label {
        color: #666666;
        font-size: 0.85rem;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        margin-bottom: 0.5rem;
    }

    .metric-value {
        color: #1A1A1A;
        font-size: 1.75rem;
        font-weight: 700;
        margin-bottom: 0.25rem;
    }

    .metric-delta {
        color: #138808;
        font-size: 0.8rem;
    }

    /* Sidebar Styling */
    .css-1d391kg, .css-1633bj2 {
        background: linear-gradient(180deg, #1A1A1A 0%, #2D2D2D 100%);
    }

    /* Sidebar text */
    .sidebar-nav {
        color: #FFFFFF !important;
        font-weight: 500;
        padding: 0.5rem 0;
    }

    /* Buttons */
    .stButton > button {
        background-color: #FF9933;
        color: #1A1A1A;
        border-radius: 8px;
        border: none;
        padding: 0.5rem 1.25rem;
        font-weight: 600;
        transition: all 0.2s;
    }

    .stButton > button:hover {
        background-color: #138808;
        color: #FFFFFF;
    }

    /* Dataframe styling */
    .dataframe {
        font-family: 'Inter', monospace;
        font-size: 0.85rem;
    }

    /* Divider */
    .custom-divider {
        border-top: 1px solid #E8E8E8;
        margin: 1.5rem 0;
    }

    /* Footer */
    .footer {
        text-align: center;
        padding: 2rem;
        color: #666666;
        font-size: 0.75rem;
        border-top: 1px solid #E8E8E8;
        margin-top: 2rem;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# DATA LOADING FUNCTION
# ============================================================================
@st.cache_data
def load_data(uploaded_file):
    """Load and process all Excel sheets"""
    try:
        monthly = pd.read_excel(uploaded_file, sheet_name="Monthly_Transactions")
        annual = pd.read_excel(uploaded_file, sheet_name="Annual_Summary")
        p2p_p2m = pd.read_excel(uploaded_file, sheet_name="P2P_vs_P2M")
        app_share = pd.read_excel(uploaded_file, sheet_name="App_Market_Share")
        fraud = pd.read_excel(uploaded_file, sheet_name="Fraud_Security")
        state_wise = pd.read_excel(uploaded_file, sheet_name="State_Wise")
        merchant = pd.read_excel(uploaded_file, sheet_name="Merchant_Categories")
        global_comp = pd.read_excel(uploaded_file, sheet_name="Global_Comparison")
        demographics = pd.read_excel(uploaded_file, sheet_name="Demographics_Adoption")

        # Process monthly data
        monthly['Date'] = pd.to_datetime(monthly['Date'], errors='coerce')
        monthly = monthly.dropna(subset=['Date'])
        monthly['Year'] = monthly['Date'].dt.year
        monthly['Month'] = monthly['Date'].dt.strftime('%b %Y')
        monthly['Quarter'] = monthly['Date'].dt.quarter
        monthly['Volume_Billions'] = monthly['Volume_Millions'] / 1000

        # Calculate metrics
        monthly['Volume_Growth_Pct'] = monthly['Volume_Millions'].pct_change() * 100
        monthly['Value_Growth_Pct'] = monthly['Value_Crore_INR'].pct_change() * 100

        # Clean other datasets
        annual = annual.dropna(subset=['Financial_Year'])
        state_wise = state_wise.dropna(subset=['State'])
        merchant = merchant.dropna(subset=['Category'])
        p2p_p2m['Date'] = pd.to_datetime(p2p_p2m['Date'], errors='coerce')
        p2p_p2m = p2p_p2m.dropna(subset=['Date'])

        return {
            'monthly': monthly,
            'annual': annual,
            'p2p': p2p_p2m,
            'app_share': app_share,
            'fraud': fraud,
            'state': state_wise,
            'merchant': merchant,
            'global': global_comp,
            'demographics': demographics
        }
    except Exception as e:
        st.error(f"Data loading error: {str(e)}")
        return None

# ============================================================================
# SIDEBAR
# ============================================================================
st.sidebar.markdown("""
<div style="text-align: center; padding: 1.5rem 0;">
    <h2 style="color: #FF9933; margin-bottom: 0.25rem;">UPI</h2>
    <p style="color: #FFFFFF; font-size: 0.85rem; opacity: 0.8;">Analytics Platform</p>
    <div style="height: 2px; background: linear-gradient(90deg, #FF9933, #138808); width: 50%; margin: 1rem auto;"></div>
</div>
""", unsafe_allow_html=True)

# Navigation
navigation = st.sidebar.radio(
    "ANALYSIS MODULES",
    [
        "Executive Dashboard",
        "Transaction Analytics",
        "P2P vs P2M Analysis",
        "Application Market Share",
        "Regional Insights",
        "Merchant Intelligence",
        "Security & Fraud Analytics",
        "Demographic Analysis",
        "Global Benchmarking"
    ],
    format_func=lambda x: x
)

# File uploader
st.sidebar.markdown("---")
st.sidebar.markdown("<p style='color: #FFFFFF; font-size: 0.8rem;'>DATA SOURCE</p>", unsafe_allow_html=True)
uploaded_file = st.sidebar.file_uploader(
    "Upload UPI Data File",
    type=['xlsx'],
    help="Upload the UPI_Dashboard_Data_2016_2025.xlsx file"
)

st.sidebar.markdown("---")
st.sidebar.markdown("""
<div style="color: #888888; font-size: 0.7rem; text-align: center;">
    <p>Data Source: NPCI | RBI</p>
    <p>Period: 2016 - 2025</p>
</div>
""", unsafe_allow_html=True)

# ============================================================================
# MAIN CONTENT
# ============================================================================
if uploaded_file is not None:
    data = load_data(uploaded_file)

    if data is None:
        st.stop()

    monthly = data['monthly']
    annual = data['annual']
    p2p = data['p2p']
    app_share = data['app_share']
    fraud = data['fraud']
    state_df = data['state']
    merchant = data['merchant']
    global_df = data['global']
    demographics = data['demographics']

    # ========================================================================
    # EXECUTIVE DASHBOARD
    # ========================================================================
    if navigation == "Executive Dashboard":
        st.markdown("<h1>Executive Dashboard</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Unified Payments Interface - Performance Overview</p>", unsafe_allow_html=True)

        # KPI Row
        latest = monthly.iloc[-1]
        total_volume_bn = monthly['Volume_Millions'].sum() / 1000
        total_value_lakh = monthly['Value_Crore_INR'].sum() / 100000

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.markdown(f"""
            <div class="metric-container">
                <div class="metric-label">Monthly Transaction Volume</div>
                <div class="metric-value">{latest['Volume_Millions']:,.0f} M</div>
                <div class="metric-delta">{latest['Month']}</div>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            st.markdown(f"""
            <div class="metric-container">
                <div class="metric-label">Monthly Transaction Value</div>
                <div class="metric-value">₹{latest['Value_Crore_INR']/1000:,.1f} K Cr</div>
                <div class="metric-delta">{latest['Month']}</div>
            </div>
            """, unsafe_allow_html=True)

        with col3:
            st.markdown(f"""
            <div class="metric-container">
                <div class="metric-label">Member Banking Institutions</div>
                <div class="metric-value">{latest['Member_Banks']:,.0f}</div>
                <div class="metric-delta">Active Participants</div>
            </div>
            """, unsafe_allow_html=True)

        with col4:
            st.markdown(f"""
            <div class="metric-container">
                <div class="metric-label">Cumulative Volume (All Time)</div>
                <div class="metric-value">{total_volume_bn:,.1f} B</div>
                <div class="metric-delta">₹{total_value_lakh:,.1f} L Cr Value</div>
            </div>
            """, unsafe_allow_html=True)

        st.markdown("<div class='custom-divider'></div>", unsafe_allow_html=True)

        # Growth Charts
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("<h3>Transaction Volume Trajectory</h3>", unsafe_allow_html=True)
            fig_vol = px.line(
                monthly, x='Date', y='Volume_Millions',
                title=None,
                labels={'Volume_Millions': 'Volume (Millions)', 'Date': ''},
                line_shape='spline'
            )
            fig_vol.update_traces(line=dict(color='#FF9933', width=2.5))
            fig_vol.update_layout(
                height=400,
                plot_bgcolor='white',
                hovermode='x unified',
                margin=dict(l=0, r=0, t=20, b=0)
            )
            fig_vol.update_xaxes(showgrid=True, gridwidth=1, gridcolor='#F0F0F0')
            fig_vol.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#F0F0F0')
            st.plotly_chart(fig_vol, use_container_width=True)

        with col2:
            st.markdown("<h3>Transaction Value Trajectory</h3>", unsafe_allow_html=True)
            fig_val = px.area(
                monthly, x='Date', y='Value_Crore_INR',
                title=None,
                labels={'Value_Crore_INR': 'Value (₹ Crore)', 'Date': ''}
            )
            fig_val.update_traces(fill='tozeroy', line=dict(color='#138808', width=2))
            fig_val.update_layout(
                height=400,
                plot_bgcolor='white',
                hovermode='x unified',
                margin=dict(l=0, r=0, t=20, b=0)
            )
            fig_val.update_xaxes(showgrid=True, gridwidth=1, gridcolor='#F0F0F0')
            fig_val.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#F0F0F0')
            st.plotly_chart(fig_val, use_container_width=True)

        st.markdown("<div class='custom-divider'></div>", unsafe_allow_html=True)

        # Annual Performance Table
        st.markdown("<h3>Annual Performance Summary</h3>", unsafe_allow_html=True)

        display_annual = annual[['Financial_Year', 'Volume_Billions', 'Value_Lakh_Crore_INR',
                                  'Active_Users_Millions', 'Member_Banks', 'P2M_Share_Pct']].copy()
        display_annual.columns = ['Financial Year', 'Volume (Billions)', 'Value (Lakh Cr)',
                                   'Active Users (M)', 'Member Banks', 'P2M Share (%)']

        st.dataframe(
            display_annual.style.format({
                'Volume (Billions)': '{:.1f}',
                'Value (Lakh Cr)': '{:.2f}',
                'Active Users (M)': '{:.0f}',
                'P2M Share (%)': '{:.1f}%'
            }).background_gradient(cmap='Oranges', subset=['Volume (Billions)']),
            use_container_width=True,
            hide_index=True
        )

    # ========================================================================
    # TRANSACTION ANALYTICS
    # ========================================================================
    elif navigation == "Transaction Analytics":
        st.markdown("<h1>Transaction Analytics</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Volume, Value, and Growth Analysis</p>", unsafe_allow_html=True)

        # Filters
        col_filter1, col_filter2 = st.columns(2)
        with col_filter1:
            years_available = sorted(monthly['Year'].unique())
            selected_years = st.multiselect("Select Financial Years", years_available, default=years_available[-3:])
        with col_filter2:
            min_date = monthly['Date'].min()
            max_date = monthly['Date'].max()
            date_range = st.date_input("Date Range", [min_date, max_date], min_value=min_date, max_value=max_date)

        # Filter data
        filtered = monthly[
            (monthly['Year'].isin(selected_years)) &
            (monthly['Date'] >= pd.to_datetime(date_range[0])) &
            (monthly['Date'] <= pd.to_datetime(date_range[1]))
        ]

        col1, col2 = st.columns(2)

        with col1:
            fig_bar = px.bar(
                filtered, x='Date', y='Volume_Millions',
                title="Monthly Transaction Volume",
                labels={'Volume_Millions': 'Volume (Millions)', 'Date': ''},
                color='Volume_Millions',
                color_continuous_scale='Oranges'
            )
            fig_bar.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_bar, use_container_width=True)

        with col2:
            # Month-over-Month Growth
            filtered['MoM_Growth'] = filtered['Volume_Millions'].pct_change() * 100
            fig_growth = px.bar(
                filtered, x='Date', y='MoM_Growth',
                title="Month-over-Month Growth Rate",
                labels={'MoM_Growth': 'Growth (%)', 'Date': ''},
                color='MoM_Growth',
                color_continuous_scale='RdYlGn'
            )
            fig_growth.add_hline(y=0, line_dash="dash", line_color="gray")
            fig_growth.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_growth, use_container_width=True)

        # Seasonal Pattern
        st.markdown("<h3>Seasonal Pattern Analysis</h3>", unsafe_allow_html=True)

        seasonal = monthly.groupby(monthly['Date'].dt.month)['Volume_Millions'].mean().reset_index()
        seasonal.columns = ['Month', 'Average_Volume']
        month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        seasonal['Month_Name'] = seasonal['Month'].apply(lambda x: month_names[x-1])

        fig_seasonal = px.bar(
            seasonal, x='Month_Name', y='Average_Volume',
            title="Average Monthly Volume - Seasonal Pattern",
            labels={'Average_Volume': 'Avg Volume (Millions)', 'Month_Name': ''},
            color='Average_Volume',
            color_continuous_scale='Greens'
        )
        fig_seasonal.update_layout(height=400, plot_bgcolor='white')
        st.plotly_chart(fig_seasonal, use_container_width=True)

    # ========================================================================
    # P2P vs P2M ANALYSIS
    # ========================================================================
    elif navigation == "P2P vs P2M Analysis":
        st.markdown("<h1>Payment Type Analysis</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Person-to-Person vs Person-to-Merchant Transaction Analysis</p>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig_p2p = go.Figure()
            fig_p2p.add_trace(go.Scatter(
                x=p2p['Date'], y=p2p['P2P_Volume_Millions'],
                name='P2P Transactions', fill='tonexty',
                line=dict(color='#FF9933', width=2)
            ))
            fig_p2p.add_trace(go.Scatter(
                x=p2p['Date'], y=p2p['P2M_Volume_Millions'],
                name='P2M Transactions', fill='tonexty',
                line=dict(color='#138808', width=2)
            ))
            fig_p2p.update_layout(
                title="Transaction Volume by Type",
                height=450, plot_bgcolor='white',
                legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
            )
            st.plotly_chart(fig_p2p, use_container_width=True)

        with col2:
            fig_share = px.area(
                p2p, x='Date', y='P2M_Vol_Share_Pct',
                title="P2M Share of Total Volume",
                labels={'P2M_Vol_Share_Pct': 'P2M Share (%)', 'Date': ''},
                color_discrete_sequence=['#FF9933']
            )
            fig_share.add_hline(y=50, line_dash="dash", line_color="#138808", annotation_text="50% Milestone")
            fig_share.add_hline(y=60, line_dash="dash", line_color="#138808", annotation_text="60% Milestone")
            fig_share.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_share, use_container_width=True)

        # Value Distribution
        st.markdown("<h3>Transaction Value Distribution (Last 12 Months)</h3>", unsafe_allow_html=True)
        last_12 = p2p.tail(12)
        fig_value = px.bar(
            last_12, x='Date', y=['P2P_Value_Crore', 'P2M_Value_Crore'],
            title=None,
            labels={'value': 'Value (₹ Crore)', 'Date': '', 'variable': 'Transaction Type'},
            barmode='group',
            color_discrete_map={'P2P_Value_Crore': '#FF9933', 'P2M_Value_Crore': '#138808'}
        )
        fig_value.update_layout(height=450, plot_bgcolor='white')
        st.plotly_chart(fig_value, use_container_width=True)

    # ========================================================================
    # APPLICATION MARKET SHARE
    # ========================================================================
    elif navigation == "Application Market Share":
        st.markdown("<h1>Application Market Share Analysis</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Third Party Application Provider Market Dynamics</p>", unsafe_allow_html=True)

        app_share['Period'] = app_share['Year'].astype(str) + " Q" + app_share['Quarter'].astype(str)

        fig_market = px.area(
            app_share, x='Period', y=['PhonePe_Pct', 'GooglePay_Pct', 'Paytm_Pct', 'Others_Pct'],
            title="Market Share Evolution (2018-2025)",
            labels={'value': 'Market Share (%)', 'Period': '', 'variable': 'Application'},
            color_discrete_map={
                'PhonePe_Pct': '#FF9933',
                'GooglePay_Pct': '#138808',
                'Paytm_Pct': '#2E86AB',
                'Others_Pct': '#95A5A6'
            }
        )
        fig_market.update_layout(height=500, plot_bgcolor='white', xaxis_tickangle=-45)
        st.plotly_chart(fig_market, use_container_width=True)

        col1, col2 = st.columns(2)

        with col1:
            latest_share = app_share.iloc[-1]
            pie_data = pd.DataFrame({
                'Application': ['PhonePe', 'Google Pay', 'Paytm', 'Others'],
                'Share': [latest_share['PhonePe_Pct'], latest_share['GooglePay_Pct'],
                          latest_share['Paytm_Pct'], latest_share['Others_Pct']]
            })
            fig_pie = px.pie(
                pie_data, values='Share', names='Application',
                title=f"Market Distribution - Q{latest_share['Quarter']} {int(latest_share['Year'])}",
                color_discrete_sequence=['#FF9933', '#138808', '#2E86AB', '#95A5A6']
            )
            fig_pie.update_traces(textposition='inside', textinfo='percent+label')
            fig_pie.update_layout(height=450)
            st.plotly_chart(fig_pie, use_container_width=True)

        with col2:
            # HHI Calculation
            hhi = (latest_share['PhonePe_Pct']**2 + latest_share['GooglePay_Pct']**2 +
                   latest_share['Paytm_Pct']**2 + latest_share['Others_Pct']**2) / 10000
            st.markdown(f"""
            <div class="professional-card">
                <h4>Market Concentration Metrics</h4>
                <div style="margin-top: 1rem;">
                    <p style="color: #666666; font-size: 0.85rem;">Herfindahl-Hirschman Index (HHI)</p>
                    <p style="font-size: 2rem; font-weight: 700; color: #FF9933;">{hhi:.3f}</p>
                    <p style="color: #666666; font-size: 0.8rem; margin-top: 1rem;">
                        HHI < 0.150: Competitive Market<br>
                        HHI 0.150-0.250: Moderate Concentration<br>
                        HHI > 0.250: High Concentration
                    </p>
                </div>
            </div>
            """, unsafe_allow_html=True)

    # ========================================================================
    # REGIONAL INSIGHTS
    # ========================================================================
    elif navigation == "Regional Insights":
        st.markdown("<h1>Regional Insights</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>State-wise UPI Adoption Analysis</p>", unsafe_allow_html=True)

        state_clean = state_df.dropna(subset=['State', 'Volume_Billions_FY25'])

        col1, col2 = st.columns(2)

        with col1:
            top_states = state_clean.nlargest(10, 'Volume_Billions_FY25')
            fig_vol_state = px.bar(
                top_states, y='State', x='Volume_Billions_FY25',
                orientation='h', title="Top 10 States by Transaction Volume",
                labels={'Volume_Billions_FY25': 'Volume (Billions)', 'State': ''},
                color='Volume_Billions_FY25',
                color_continuous_scale='Oranges',
                text='Volume_Billions_FY25'
            )
            fig_vol_state.update_traces(texttemplate='%{text:.1f}', textposition='outside')
            fig_vol_state.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_vol_state, use_container_width=True)

        with col2:
            fig_per_capita = px.bar(
                top_states, y='State', x='Per_Capita_Txns_FY25',
                orientation='h', title="Transactions Per Capita",
                labels={'Per_Capita_Txns_FY25': 'Transactions Per Person', 'State': ''},
                color='Per_Capita_Txns_FY25',
                color_continuous_scale='Greens',
                text='Per_Capita_Txns_FY25'
            )
            fig_per_capita.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig_per_capita.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_per_capita, use_container_width=True)

        # Tier Analysis
        st.markdown("<h3>Adoption by Market Tier</h3>", unsafe_allow_html=True)
        tier_summary = state_clean.groupby('Tier').agg({
            'Volume_Billions_FY25': 'sum',
            'Per_Capita_Txns_FY25': 'mean'
        }).reset_index()

        fig_tier = px.bar(
            tier_summary, x='Tier', y='Volume_Billions_FY25',
            title="Total Volume by Market Classification",
            labels={'Volume_Billions_FY25': 'Total Volume (Billions)', 'Tier': ''},
            color='Volume_Billions_FY25',
            color_continuous_scale='Oranges',
            text='Volume_Billions_FY25'
        )
        fig_tier.update_traces(texttemplate='%{text:.1f}', textposition='outside')
        fig_tier.update_layout(height=400, plot_bgcolor='white')
        st.plotly_chart(fig_tier, use_container_width=True)

    # ========================================================================
    # MERCHANT INTELLIGENCE
    # ========================================================================
    elif navigation == "Merchant Intelligence":
        st.markdown("<h1>Merchant Intelligence</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Category-wise Transaction Analysis</p>", unsafe_allow_html=True)

        top_merchants = merchant.nlargest(10, 'Value_Crore')

        col1, col2 = st.columns(2)

        with col1:
            fig_value_merchant = px.bar(
                top_merchants, y='Category', x='Value_Crore',
                orientation='h', title="Top Categories by Transaction Value",
                labels={'Value_Crore': 'Value (₹ Crore)', 'Category': ''},
                color='Value_Crore',
                color_continuous_scale='Oranges',
                text='Value_Crore'
            )
            fig_value_merchant.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig_value_merchant.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_value_merchant, use_container_width=True)

        with col2:
            fig_ticket = px.bar(
                top_merchants, y='Category', x='Avg_Ticket_INR',
                orientation='h', title="Average Transaction Value by Category",
                labels={'Avg_Ticket_INR': 'Average Ticket (₹)', 'Category': ''},
                color='Avg_Ticket_INR',
                color_continuous_scale='Greens',
                text='Avg_Ticket_INR'
            )
            fig_ticket.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig_ticket.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_ticket, use_container_width=True)

        # Scatter Plot Matrix
        st.markdown("<h3>Category Performance Matrix</h3>", unsafe_allow_html=True)
        fig_scatter = px.scatter(
            merchant, x='Volume_Millions', y='Value_Crore',
            size='Avg_Ticket_INR', color='Category',
            title="Volume vs Value Analysis by Merchant Category",
            labels={'Volume_Millions': 'Transaction Volume (Millions)', 'Value_Crore': 'Transaction Value (₹ Crore)'},
            hover_data=['Avg_Ticket_INR']
        )
        fig_scatter.update_layout(height=500, plot_bgcolor='white')
        st.plotly_chart(fig_scatter, use_container_width=True)

    # ========================================================================
    # SECURITY & FRAUD ANALYTICS
    # ========================================================================
    elif navigation == "Security & Fraud Analytics":
        st.markdown("<h1>Security & Fraud Analytics</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Transaction Security and Risk Metrics</p>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig_fraud_cases = px.bar(
                fraud, x='Financial_Year', y='Fraud_Cases',
                title="Fraud Incidents by Financial Year",
                labels={'Fraud_Cases': 'Number of Cases', 'Financial_Year': ''},
                color='Fraud_Cases',
                color_continuous_scale='Reds',
                text='Fraud_Cases'
            )
            fig_fraud_cases.update_traces(texttemplate='%{text:,.0f}', textposition='outside')
            fig_fraud_cases.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_fraud_cases, use_container_width=True)

        with col2:
            fig_fraud_rate = px.line(
                fraud, x='Financial_Year', y='Fraud_Rate_Pct',
                title="Fraud Rate as Percentage of Transactions",
                labels={'Fraud_Rate_Pct': 'Fraud Rate (%)', 'Financial_Year': ''},
                markers=True,
                color_discrete_sequence=['#FF9933']
            )
            fig_fraud_rate.add_hline(y=0.001, line_dash="dash", line_color="#138808", annotation_text="Industry Benchmark")
            fig_fraud_rate.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_fraud_rate, use_container_width=True)

        col1, col2 = st.columns(2)

        with col1:
            fig_odr = px.bar(
                fraud, x='Financial_Year', y='ODR_Resolution_Rate_Pct',
                title="ODR Resolution Rate",
                labels={'ODR_Resolution_Rate_Pct': 'Resolution Rate (%)', 'Financial_Year': ''},
                color='ODR_Resolution_Rate_Pct',
                color_continuous_scale='Greens',
                text='ODR_Resolution_Rate_Pct'
            )
            fig_odr.update_traces(texttemplate='%{text:.0f}%', textposition='outside')
            fig_odr.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_odr, use_container_width=True)

        with col2:
            fig_amount = px.line(
                fraud, x='Financial_Year', y='Fraud_Amount_Per_Case_INR',
                title="Average Fraud Amount per Case",
                labels={'Fraud_Amount_Per_Case_INR': 'Amount per Case (₹)', 'Financial_Year': ''},
                markers=True,
                color_discrete_sequence=['#2E86AB']
            )
            fig_amount.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_amount, use_container_width=True)

    # ========================================================================
    # DEMOGRAPHIC ANALYSIS
    # ========================================================================
    elif navigation == "Demographic Analysis":
        st.markdown("<h1>Demographic Analysis</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>Age-wise UPI Adoption and Usage Patterns</p>", unsafe_allow_html=True)

        fig_adoption = go.Figure()
        fig_adoption.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2025'],
            name='2025', marker_color='#FF9933'
        ))
        fig_adoption.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2022'],
            name='2022', marker_color='#138808'
        ))
        fig_adoption.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2019'],
            name='2019', marker_color='#2E86AB'
        ))
        fig_adoption.update_layout(
            title="UPI Adoption Rate by Age Group",
            xaxis_title="Age Group", yaxis_title="Adoption Rate (%)",
            barmode='group', height=500, plot_bgcolor='white'
        )
        st.plotly_chart(fig_adoption, use_container_width=True)

        col1, col2 = st.columns(2)

        with col1:
            fig_daily = px.bar(
                demographics, x='Age_Group', y='Avg_Daily_Txns',
                title="Average Daily Transactions by Age Group",
                labels={'Avg_Daily_Txns': 'Daily Transactions', 'Age_Group': ''},
                color='Avg_Daily_Txns',
                color_continuous_scale='Oranges',
                text='Avg_Daily_Txns'
            )
            fig_daily.update_traces(texttemplate='%{text:.1f}', textposition='outside')
            fig_daily.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_daily, use_container_width=True)

        with col2:
            fig_trust = px.line(
                demographics, x='Age_Group', y='Trust_Score_Pct',
                title="Trust Score by Age Group",
                labels={'Trust_Score_Pct': 'Trust Score (%)', 'Age_Group': ''},
                markers=True,
                color_discrete_sequence=['#138808']
            )
            fig_trust.add_hline(y=80, line_dash="dash", line_color="#FF9933", annotation_text="High Trust Threshold")
            fig_trust.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig_trust, use_container_width=True)

    # ========================================================================
    # GLOBAL BENCHMARKING
    # ========================================================================
    elif navigation == "Global Benchmarking":
        st.markdown("<h1>Global Benchmarking</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color: #666666; margin-bottom: 2rem;'>India vs Global Real-Time Payment Systems</p>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig_global = px.bar(
                global_df, x='Country', y='Annual_Txn_Billions_2023',
                title="Annual Real-Time Payment Transactions (2023)",
                labels={'Annual_Txn_Billions_2023': 'Transactions (Billions)', 'Country': ''},
                color='Real_Time_Share_Pct',
                color_continuous_scale='Oranges',
                hover_data=['Payment_System', 'Launch_Year']
            )
            fig_global.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_global, use_container_width=True)

        with col2:
            fig_share_global = px.bar(
                global_df, x='Country', y='Real_Time_Share_Pct',
                title="Real-Time Payment Share by Country",
                labels={'Real_Time_Share_Pct': 'Real-Time Share (%)', 'Country': ''},
                color='Launch_Year',
                color_continuous_scale='Greens'
            )
            fig_share_global.update_layout(height=500, plot_bgcolor='white')
            st.plotly_chart(fig_share_global, use_container_width=True)

        # India Leadership Card
        st.markdown("""
        <div class="professional-card" style="background: linear-gradient(135deg, #1A1A1A 0%, #2D2D2D 100%); color: white; margin-top: 1rem;">
            <h3 style="color: #FF9933;">India Leadership Position</h3>
            <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-top: 1rem;">
                <div>
                    <p style="color: #888888; font-size: 0.75rem;">Global Rank</p>
                    <p style="font-size: 1.5rem; font-weight: 700;">#2</p>
                    <p style="color: #888888; font-size: 0.7rem;">Largest Market</p>
                </div>
                <div>
                    <p style="color: #888888; font-size: 0.75rem;">Real-Time Share</p>
                    <p style="font-size: 1.5rem; font-weight: 700;">84%</p>
                    <p style="color: #888888; font-size: 0.7rem;">Highest Globally</p>
                </div>
                <div>
                    <p style="color: #888888; font-size: 0.75rem;">Launch Year</p>
                    <p style="font-size: 1.5rem; font-weight: 700;">2016</p>
                    <p style="color: #888888; font-size: 0.7rem;">Industry Pioneer</p>
                </div>
                <div>
                    <p style="color: #888888; font-size: 0.75rem;">Market Position</p>
                    <p style="font-size: 1.5rem; font-weight: 700;">Leader</p>
                    <p style="color: #888888; font-size: 0.7rem;">Global Benchmark</p>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<h3>Comparative Analysis</h3>", unsafe_allow_html=True)
        st.dataframe(
            global_df[['Country', 'Payment_System', 'Annual_Txn_Billions_2023', 'Real_Time_Share_Pct', 'Launch_Year']]
            .style.format({
                'Annual_Txn_Billions_2023': '{:.1f}',
                'Real_Time_Share_Pct': '{:.0f}%'
            }).background_gradient(cmap='Oranges', subset=['Annual_Txn_Billions_2023']),
            use_container_width=True,
            hide_index=True
        )

    # Footer
    st.markdown("""
    <div class="footer">
        <p>Data Sources: NPCI Official Statistics | Reserve Bank of India | Ministry of Finance</p>
        <p>Unified Payments Interface Analytics Platform | Period: 2016 - 2025</p>
    </div>
    """, unsafe_allow_html=True)

else:
    # No file uploaded state
    st.markdown("""
    <div style="display: flex; justify-content: center; align-items: center; min-height: 60vh; text-align: center;">
        <div>
            <div style="font-size: 4rem; margin-bottom: 1rem;">📊</div>
            <h2>UPI Analytics Platform</h2>
            <p style="color: #666666; margin: 1rem 0;">Please upload the UPI data file to begin analysis</p>
            <div style="height: 2px; background: linear-gradient(90deg, #FF9933, #138808); width: 100px; margin: 1rem auto;"></div>
            <p style="color: #888888; font-size: 0.8rem; margin-top: 1rem;">Supported format: Excel (.xlsx)</p>
        </div>
    </div>
    """, unsafe_allow_html=True)