# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts__E4Gu7Sr2QpOtlEa6gGSyzmf8QY6x
"""

"""
UPI DASHBOARD 2016-2025
Single Page Professional Analytics Platform
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

# ============================================================================
# PAGE CONFIGURATION
# ============================================================================
st.set_page_config(
    page_title="UPI Analytics Dashboard 2016-2025",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Black and White Theme - Charts use Orange and Green only
st.markdown("""
<style>
    /* Main container */
    .main {
        background-color: #FFFFFF;
    }

    /* All text black */
    .stMarkdown, .stMetric, .stText, .stDataFrame, p, h1, h2, h3, h4, h5, h6, label, span {
        color: #000000 !important;
    }

    /* Headers */
    h1, h2, h3 {
        color: #000000 !important;
        font-weight: 600;
    }

    /* Metric Cards */
    .metric-card {
        background: #F8F9FA;
        border-radius: 8px;
        padding: 1rem;
        border: 1px solid #E0E0E0;
    }

    .metric-label {
        color: #000000;
        font-size: 0.8rem;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .metric-value {
        color: #000000;
        font-size: 1.8rem;
        font-weight: 700;
    }

    /* Divider */
    hr {
        border-top: 1px solid #E0E0E0;
    }

    /* Sidebar - minimal */
    .css-1d391kg {
        background-color: #F8F9FA;
    }

    /* File uploader */
    .stFileUploader {
        border: 1px dashed #CCCCCC;
        border-radius: 8px;
        padding: 1rem;
    }

    /* Dataframe */
    .dataframe {
        font-size: 0.8rem;
    }

    /* Footer */
    .footer {
        text-align: center;
        padding: 1.5rem;
        color: #666666;
        font-size: 0.7rem;
        border-top: 1px solid #E0E0E0;
        margin-top: 2rem;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# HEADER
# ============================================================================
st.markdown("<h1 style='text-align: center;'>UNIFIED PAYMENTS INTERFACE</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #666666; margin-bottom: 2rem;'>India's Digital Payment Revolution | 2016 - 2025</p>", unsafe_allow_html=True)
st.markdown("<hr>", unsafe_allow_html=True)

# ============================================================================
# DATA LOADING
# ============================================================================
@st.cache_data
def load_data(uploaded_file):
    """Load all sheets from Excel file"""
    try:
        monthly = pd.read_excel(uploaded_file, sheet_name="Monthly_Transactions")
        annual = pd.read_excel(uploaded_file, sheet_name="Annual_Summary")
        p2p_p2m = pd.read_excel(uploaded_file, sheet_name="P2P_vs_P2M")
        app_share = pd.read_excel(uploaded_file, sheet_name="App_Market_Share")
        fraud = pd.read_excel(uploaded_file, sheet_name="Fraud_Security")
        state_wise = pd.read_excel(uploaded_file, sheet_name="State_Wise")
        merchant = pd.read_excel(uploaded_file, sheet_name="Merchant_Categories")
        global_comp = pd.read_excel(uploaded_file, sheet_name="Global_Comparison")
        demographics = pd.read_excel(uploaded_file, sheet_name="Demographics_Adoption")

        # Clean monthly data
        monthly['Date'] = pd.to_datetime(monthly['Date'], errors='coerce')
        monthly = monthly.dropna(subset=['Date'])
        monthly['Year'] = monthly['Date'].dt.year
        monthly['Month_Name'] = monthly['Date'].dt.strftime('%b')

        # Clean other sheets
        annual = annual.dropna(subset=['Financial_Year'])
        state_wise = state_wise.dropna(subset=['State'])
        merchant = merchant.dropna(subset=['Category'])
        p2p_p2m['Date'] = pd.to_datetime(p2p_p2m['Date'], errors='coerce')
        p2p_p2m = p2p_p2m.dropna(subset=['Date'])

        return monthly, annual, p2p_p2m, app_share, fraud, state_wise, merchant, global_comp, demographics

    except Exception as e:
        st.error(f"Error loading data: {str(e)}")
        return None, None, None, None, None, None, None, None, None

# File uploader
uploaded_file = st.file_uploader("Upload UPI Data File (Excel)", type=['xlsx'])

if uploaded_file is not None:
    monthly, annual, p2p_p2m, app_share, fraud, state_wise, merchant, global_comp, demographics = load_data(uploaded_file)

    if monthly is not None:

        # ====================================================================
        # KPI ROW - Top 4 Metrics
        # ====================================================================
        latest = monthly.iloc[-1]
        total_volume_bn = monthly['Volume_Millions'].sum() / 1000
        total_value_lakh = monthly['Value_Crore_INR'].sum() / 100000

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-label">Monthly Volume</div>
                <div class="metric-value">{latest['Volume_Millions']:,.0f} M</div>
                <div style="font-size: 0.7rem;">{latest['Month_Name']} {latest['Year']}</div>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-label">Monthly Value</div>
                <div class="metric-value">₹{latest['Value_Crore_INR']/1000:,.1f} K Cr</div>
                <div style="font-size: 0.7rem;">{latest['Month_Name']} {latest['Year']}</div>
            </div>
            """, unsafe_allow_html=True)

        with col3:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-label">Member Banks</div>
                <div class="metric-value">{latest['Member_Banks']:,.0f}</div>
                <div style="font-size: 0.7rem;">Active Participants</div>
            </div>
            """, unsafe_allow_html=True)

        with col4:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-label">Cumulative Volume</div>
                <div class="metric-value">{total_volume_bn:,.1f} B</div>
                <div style="font-size: 0.7rem;">All Time</div>
            </div>
            """, unsafe_allow_html=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 1: Volume & Value Trends (Line Chart)
        # ====================================================================
        st.markdown("<h3>Transaction Volume & Value Trends</h3>", unsafe_allow_html=True)

        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(
            x=monthly['Date'], y=monthly['Volume_Millions'],
            name='Volume (Millions)',
            line=dict(color='#FF9933', width=2.5)
        ))
        fig1.add_trace(go.Scatter(
            x=monthly['Date'], y=monthly['Value_Crore_INR'] / 1000,
            name='Value (Thousand Crore)',
            line=dict(color='#138808', width=2.5),
            yaxis='y2'
        ))
        fig1.update_layout(
            height=450,
            plot_bgcolor='white',
            hovermode='x unified',
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
            xaxis=dict(title='Year', showgrid=True, gridcolor='#F0F0F0'),
            yaxis=dict(title='Volume (Millions)', showgrid=True, gridcolor='#F0F0F0'),
            yaxis2=dict(title='Value (Thousand Crore)', overlaying='y', side='right')
        )
        st.plotly_chart(fig1, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 2: P2P vs P2M (Stacked Area)
        # ====================================================================
        st.markdown("<h3>Payment Type Analysis: P2P vs P2M</h3>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig2 = go.Figure()
            fig2.add_trace(go.Scatter(
                x=p2p_p2m['Date'], y=p2p_p2m['P2P_Volume_Millions'],
                name='P2P (Person to Person)',
                fill='tonexty',
                line=dict(color='#FF9933', width=1)
            ))
            fig2.add_trace(go.Scatter(
                x=p2p_p2m['Date'], y=p2p_p2m['P2M_Volume_Millions'],
                name='P2M (Person to Merchant)',
                fill='tonexty',
                line=dict(color='#138808', width=1)
            ))
            fig2.update_layout(
                height=400,
                plot_bgcolor='white',
                hovermode='x unified',
                legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
                xaxis=dict(title='Year', showgrid=True, gridcolor='#F0F0F0'),
                yaxis=dict(title='Volume (Millions)', showgrid=True, gridcolor='#F0F0F0')
            )
            st.plotly_chart(fig2, use_container_width=True)

        with col2:
            fig3 = px.area(
                p2p_p2m, x='Date', y='P2M_Vol_Share_Pct',
                title=None,
                labels={'P2M_Vol_Share_Pct': 'P2M Share (%)', 'Date': 'Year'},
                color_discrete_sequence=['#FF9933']
            )
            fig3.add_hline(y=50, line_dash='dash', line_color='#138808', annotation_text='50%')
            fig3.add_hline(y=60, line_dash='dash', line_color='#138808', annotation_text='60%')
            fig3.update_layout(
                height=400,
                plot_bgcolor='white',
                xaxis=dict(showgrid=True, gridcolor='#F0F0F0'),
                yaxis=dict(title='Share of Total Volume (%)', showgrid=True, gridcolor='#F0F0F0')
            )
            st.plotly_chart(fig3, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 3: App Market Share
        # ====================================================================
        st.markdown("<h3>Application Market Share Evolution</h3>", unsafe_allow_html=True)

        app_share['Period'] = app_share['Year'].astype(str) + " Q" + app_share['Quarter'].astype(str)

        fig4 = px.area(
            app_share, x='Period', y=['PhonePe_Pct', 'GooglePay_Pct', 'Paytm_Pct', 'Others_Pct'],
            labels={'value': 'Market Share (%)', 'Period': '', 'variable': 'Application'},
            color_discrete_map={
                'PhonePe_Pct': '#FF9933',
                'GooglePay_Pct': '#138808',
                'Paytm_Pct': '#2E86AB',
                'Others_Pct': '#95A5A6'
            }
        )
        fig4.update_layout(
            height=450,
            plot_bgcolor='white',
            xaxis_tickangle=-45,
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
        )
        st.plotly_chart(fig4, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 4: Top States (Two Charts Side by Side)
        # ====================================================================
        st.markdown("<h3>Regional Analysis: Top Performing States</h3>", unsafe_allow_html=True)

        state_clean = state_wise.dropna(subset=['State', 'Volume_Billions_FY25'])
        top_states = state_clean.nlargest(10, 'Volume_Billions_FY25')

        col1, col2 = st.columns(2)

        with col1:
            fig5 = px.bar(
                top_states, y='State', x='Volume_Billions_FY25',
                orientation='h', title='Top 10 States by Transaction Volume',
                labels={'Volume_Billions_FY25': 'Volume (Billions)', 'State': ''},
                color='Volume_Billions_FY25',
                color_continuous_scale='Oranges',
                text='Volume_Billions_FY25'
            )
            fig5.update_traces(texttemplate='%{text:.1f}', textposition='outside')
            fig5.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig5, use_container_width=True)

        with col2:
            fig6 = px.bar(
                top_states, y='State', x='Per_Capita_Txns_FY25',
                orientation='h', title='Transactions Per Capita',
                labels={'Per_Capita_Txns_FY25': 'Transactions Per Person', 'State': ''},
                color='Per_Capita_Txns_FY25',
                color_continuous_scale='Greens',
                text='Per_Capita_Txns_FY25'
            )
            fig6.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig6.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig6, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 5: Merchant Categories
        # ====================================================================
        st.markdown("<h3>Merchant Category Intelligence</h3>", unsafe_allow_html=True)

        top_merchants = merchant.nlargest(10, 'Value_Crore')

        col1, col2 = st.columns(2)

        with col1:
            fig7 = px.bar(
                top_merchants, y='Category', x='Value_Crore',
                orientation='h', title='Top Categories by Transaction Value',
                labels={'Value_Crore': 'Value (₹ Crore)', 'Category': ''},
                color='Value_Crore',
                color_continuous_scale='Oranges',
                text='Value_Crore'
            )
            fig7.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig7.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig7, use_container_width=True)

        with col2:
            fig8 = px.bar(
                top_merchants, y='Category', x='Avg_Ticket_INR',
                orientation='h', title='Average Transaction Value by Category',
                labels={'Avg_Ticket_INR': 'Average Ticket (₹)', 'Category': ''},
                color='Avg_Ticket_INR',
                color_continuous_scale='Greens',
                text='Avg_Ticket_INR'
            )
            fig8.update_traces(texttemplate='%{text:.0f}', textposition='outside')
            fig8.update_layout(height=450, plot_bgcolor='white')
            st.plotly_chart(fig8, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 6: Fraud & Security
        # ====================================================================
        st.markdown("<h3>Security & Fraud Analytics</h3>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig9 = px.bar(
                fraud, x='Financial_Year', y='Fraud_Cases',
                title='Fraud Incidents by Financial Year',
                labels={'Fraud_Cases': 'Number of Cases', 'Financial_Year': ''},
                color='Fraud_Cases',
                color_continuous_scale='Oranges',
                text='Fraud_Cases'
            )
            fig9.update_traces(texttemplate='%{text:,.0f}', textposition='outside')
            fig9.update_layout(height=400, plot_bgcolor='white')
            st.plotly_chart(fig9, use_container_width=True)

        with col2:
            fig10 = px.line(
                fraud, x='Financial_Year', y='Fraud_Rate_Pct',
                title='Fraud Rate (% of Total Transactions)',
                labels={'Fraud_Rate_Pct': 'Fraud Rate (%)', 'Financial_Year': ''},
                markers=True,
                color_discrete_sequence=['#FF9933']
            )
            fig10.add_hline(y=0.001, line_dash='dash', line_color='#138808', annotation_text='Industry Benchmark')
            fig10.update_layout(height=400, plot_bgcolor='white')
            st.plotly_chart(fig10, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 7: Demographics
        # ====================================================================
        st.markdown("<h3>Demographic Adoption Patterns</h3>", unsafe_allow_html=True)

        fig11 = go.Figure()
        fig11.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2025'],
            name='2025', marker_color='#FF9933'
        ))
        fig11.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2022'],
            name='2022', marker_color='#138808'
        ))
        fig11.add_trace(go.Bar(
            x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2019'],
            name='2019', marker_color='#2E86AB'
        ))
        fig11.update_layout(
            height=450,
            plot_bgcolor='white',
            xaxis_title='Age Group',
            yaxis_title='Adoption Rate (%)',
            barmode='group',
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
        )
        st.plotly_chart(fig11, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # CHART 8: Global Benchmark
        # ====================================================================
        st.markdown("<h3>Global Benchmarking</h3>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            fig12 = px.bar(
                global_comp, x='Country', y='Annual_Txn_Billions_2023',
                title='Annual Real-Time Payment Transactions (2023)',
                labels={'Annual_Txn_Billions_2023': 'Transactions (Billions)', 'Country': ''},
                color='Real_Time_Share_Pct',
                color_continuous_scale='Oranges',
                hover_data=['Payment_System']
            )
            fig12.update_layout(height=450, plot_bgcolor='white', xaxis_tickangle=-45)
            st.plotly_chart(fig12, use_container_width=True)

        with col2:
            fig13 = px.bar(
                global_comp, x='Country', y='Real_Time_Share_Pct',
                title='Real-Time Payment Share by Country',
                labels={'Real_Time_Share_Pct': 'Share (%)', 'Country': ''},
                color='Launch_Year',
                color_continuous_scale='Greens'
            )
            fig13.update_layout(height=450, plot_bgcolor='white', xaxis_tickangle=-45)
            st.plotly_chart(fig13, use_container_width=True)

        st.markdown("<hr>", unsafe_allow_html=True)

        # ====================================================================
        # ANNUAL SUMMARY TABLE
        # ====================================================================
        st.markdown("<h3>Annual Performance Summary</h3>", unsafe_allow_html=True)

        display_annual = annual[['Financial_Year', 'Volume_Billions', 'Value_Lakh_Crore_INR',
                                  'Active_Users_Millions', 'Member_Banks', 'P2M_Share_Pct']].copy()
        display_annual.columns = ['Financial Year', 'Volume (Billions)', 'Value (Lakh Cr)',
                                   'Active Users (Millions)', 'Member Banks', 'P2M Share (%)']

        st.dataframe(
            display_annual.style.format({
                'Volume (Billions)': '{:.1f}',
                'Value (Lakh Cr)': '{:.2f}',
                'Active Users (Millions)': '{:.0f}',
                'P2M Share (%)': '{:.1f}%'
            }),
            use_container_width=True,
            hide_index=True
        )

        # ====================================================================
        # FOOTER
        # ====================================================================
        st.markdown("""
        <div class="footer">
            Data Sources: NPCI Official Statistics | Reserve Bank of India | Ministry of Finance<br>
            Unified Payments Interface Analytics Platform | 2016 - 2025
        </div>
        """, unsafe_allow_html=True)

    else:
        st.error("Unable to load data. Please check the file format.")

else:
    # No file uploaded
    st.markdown("""
    <div style="text-align: center; padding: 3rem;">
        <h2>UPI Analytics Dashboard</h2>
        <p style="color: #666666;">Please upload the UPI data file (Excel format) to begin analysis</p>
        <div style="height: 2px; background: #E0E0E0; width: 100px; margin: 1rem auto;"></div>
        <p style="color: #888888; font-size: 0.8rem;">Supported file: UPI_Dashboard_Data_2016_2025.xlsx</p>
    </div>
    """, unsafe_allow_html=True)