# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts__E4Gu7Sr2QpOtlEa6gGSyzmf8QY6x
"""

"""
UPI DASHBOARD 2016-2025
Creative dashboard with UPI brand colors
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
from datetime import datetime

# ============================================================================
# PAGE CONFIGURATION - UPI Theme Colors
# ============================================================================
st.set_page_config(
    page_title="UPI Dashboard 2016-2025",
    page_icon="🇮🇳",
    layout="wide",
    initial_sidebar_state="expanded"
)

# UPI Brand Colors
UPI_COLORS = {
    "primary": "#1A237E",      # Deep Blue
    "secondary": "#FF9933",     # Saffron (India flag)
    "accent": "#138808",        # Green (India flag)
    "white": "#FFFFFF",
    "background": "#F5F7FA",
    "success": "#00C853",
    "warning": "#FF6D00",
    "danger": "#D32F2F",
    "info": "#0288D1",
    "gradient_1": "#2196F3",
    "gradient_2": "#9C27B0"
}

# Custom CSS for UPI Theme
st.markdown(f"""
<style>
    /* Main container */
    .main {{
        background-color: {UPI_COLORS['background']};
    }}

    /* Headers */
    h1, h2, h3 {{
        color: {UPI_COLORS['primary']} !important;
        font-family: 'Segoe UI', sans-serif;
    }}

    /* Cards */
    .css-1r6slb0 {{
        background: linear-gradient(135deg, {UPI_COLORS['primary']}, {UPI_COLORS['gradient_1']});
        border-radius: 15px;
        padding: 20px;
        color: white;
    }}

    /* Metric Cards */
    .metric-card {{
        background: linear-gradient(135deg, {UPI_COLORS['white']}, #E8EAF6);
        border-radius: 15px;
        padding: 20px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        border-left: 5px solid {UPI_COLORS['secondary']};
    }}

    /* Sidebar */
    .css-1d391kg {{
        background: linear-gradient(180deg, {UPI_COLORS['primary']}, {UPI_COLORS['gradient_2']});
    }}

    /* Buttons */
    .stButton > button {{
        background: linear-gradient(135deg, {UPI_COLORS['secondary']}, {UPI_COLORS['accent']});
        color: white;
        border-radius: 25px;
        border: none;
        padding: 10px 25px;
        font-weight: bold;
    }}
</style>
""", unsafe_allow_html=True)

# ============================================================================
# LOAD DATA WITH CACHING
# ============================================================================
@st.cache_data
def load_all_data():
    """Load all sheets from Excel file"""
    file_path = "UPI_Dashboard_Data_2016_2025.xlsx"

    try:
        monthly = pd.read_excel(file_path, sheet_name="Monthly_Transactions")
        annual = pd.read_excel(file_path, sheet_name="Annual_Summary")
        p2p_p2m = pd.read_excel(file_path, sheet_name="P2P_vs_P2M")
        app_share = pd.read_excel(file_path, sheet_name="App_Market_Share")
        fraud = pd.read_excel(file_path, sheet_name="Fraud_Security")
        state_wise = pd.read_excel(file_path, sheet_name="State_Wise")
        merchant = pd.read_excel(file_path, sheet_name="Merchant_Categories")
        global_comp = pd.read_excel(file_path, sheet_name="Global_Comparison")
        demographics = pd.read_excel(file_path, sheet_name="Demographics_Adoption")

        # Data cleaning
        monthly['Date'] = pd.to_datetime(monthly['Date'], errors='coerce')
        monthly = monthly.dropna(subset=['Date'])
        monthly['Year'] = monthly['Date'].dt.year
        monthly['Month_Name'] = monthly['Date'].dt.strftime('%B')
        monthly['Quarter'] = monthly['Date'].dt.quarter

        # Calculate growth rates
        monthly['Volume_MoM_Pct'] = monthly['Volume_Millions'].pct_change() * 100
        monthly['Value_MoM_Pct'] = monthly['Value_Crore_INR'].pct_change() * 100

        # Clean other sheets
        annual = annual.dropna(subset=['Financial_Year'])
        state_wise = state_wise.dropna(subset=['State'])
        merchant = merchant.dropna(subset=['Category'])

        # Clean P2P data
        p2p_p2m['Date'] = pd.to_datetime(p2p_p2m['Date'], errors='coerce')
        p2p_p2m = p2p_p2m.dropna(subset=['Date'])

        return monthly, annual, p2p_p2m, app_share, fraud, state_wise, merchant, global_comp, demographics

    except Exception as e:
        st.error(f"❌ Error loading data: {e}")
        st.info("Please make sure the Excel file is in the same directory")
        return None, None, None, None, None, None, None, None, None

# Load data
monthly, annual, p2p_p2m, app_share, fraud, state_wise, merchant, global_comp, demographics = load_all_data()

if monthly is None:
    st.stop()

# ============================================================================
# SIDEBAR NAVIGATION
# ============================================================================
st.sidebar.markdown(f"""
<div style="text-align: center; padding: 20px;">
    <h2 style="color: white;">🇮🇳 UPI</h2>
    <h4 style="color: {UPI_COLORS['secondary']};">Digital India</h4>
    <hr style="border-color: {UPI_COLORS['accent']};">
</div>
""", unsafe_allow_html=True)

# Navigation menu with icons
pages = {
    "🏠 Home": "home",
    "📊 Growth Analytics": "growth",
    "🔄 P2P vs P2M": "p2p",
    "📱 App Market Share": "apps",
    "🗺️ State Insights": "states",
    "🛒 Merchant Analysis": "merchant",
    "🔒 Security Dashboard": "security",
    "👥 Demographics": "demographics",
    "🌍 Global Benchmark": "global"
}

selected_page = st.sidebar.radio(
    "📌 NAVIGATION",
    list(pages.keys()),
    format_func=lambda x: x
)

# Sidebar filters
st.sidebar.markdown("---")
st.sidebar.markdown("### 🎛️ Filters")

# Year filter for monthly data
years = sorted(monthly['Year'].unique())
selected_years = st.sidebar.multiselect(
    "Select Years",
    years,
    default=years[-3:]  # Last 3 years
)

# Date range filter
min_date = monthly['Date'].min()
max_date = monthly['Date'].max()
date_range = st.sidebar.date_input(
    "Date Range",
    [min_date, max_date],
    min_value=min_date,
    max_value=max_date
)

# Apply filters
filtered_monthly = monthly[
    (monthly['Year'].isin(selected_years)) &
    (monthly['Date'] >= pd.to_datetime(date_range[0])) &
    (monthly['Date'] <= pd.to_datetime(date_range[1]))
]

# Footer
st.sidebar.markdown("---")
st.sidebar.markdown(f"""
<div style="text-align: center; color: white;">
    <small>Data Source: NPCI, RBI<br>
    2016-2025 | Made with ❤️</small>
</div>
""", unsafe_allow_html=True)

# ============================================================================
# MAIN CONTENT
# ============================================================================

# Hero Section
col1, col2, col3 = st.columns([2, 1, 1])
with col1:
    st.markdown(f"""
    <h1 style='color: {UPI_COLORS["primary"]};'>
        🇮🇳 Unified Payments Interface
    </h1>
    <h3 style='color: {UPI_COLORS["accent"]};'>
        India's Digital Payment Revolution
    </h3>
    <p style='font-size: 18px;'>
        Comprehensive analytics from inception (2016) to 2025
    </p>
    """, unsafe_allow_html=True)

# KPI Row (Always visible)
latest = filtered_monthly.iloc[-1] if not filtered_monthly.empty else monthly.iloc[-1]
total_volume = filtered_monthly['Volume_Millions'].sum() / 1000
total_value = filtered_monthly['Value_Crore_INR'].sum() / 100000

col1, col2, col3, col4, col5 = st.columns(5)
with col1:
    st.metric("📊 Total Volume", f"{total_volume:.1f}B",
              delta=f"+{filtered_monthly['Volume_Millions'].pct_change().mean()*100:.1f}%")
with col2:
    st.metric("💰 Total Value", f"₹{total_value:.1f}L Cr")
with col3:
    st.metric("🏦 Member Banks", f"{latest['Member_Banks']}")
with col4:
    st.metric("📈 Avg Ticket", f"₹{latest.get('Avg_Ticket_INR', 'N/A')}")
with col5:
    st.metric("📅 Latest Month", f"{latest['Month_Name']} {latest['Year']}")

st.markdown("---")

# ============================================================================
# PAGE CONTENT
# ============================================================================

# HOME PAGE
if selected_page == "🏠 Home":
    st.markdown(f"""
    <div style="background: linear-gradient(135deg, {UPI_COLORS['primary']}, {UPI_COLORS['gradient_1']});
                border-radius: 20px; padding: 30px; color: white; margin-bottom: 30px;">
        <h2 style="color: white;">🎯 Welcome to UPI Dashboard</h2>
        <p style="font-size: 18px;">
            Explore India's digital payment journey from 2016 to 2025.
            Track growth, understand user behavior, and analyze market trends.
        </p>
    </div>
    """, unsafe_allow_html=True)

    # Quick Stats Grid
    col1, col2, col3 = st.columns(3)

    with col1:
        # YoY Growth
        yoy_growth = filtered_monthly['Volume_Millions'].iloc[-1] / filtered_monthly['Volume_Millions'].iloc[0] - 1
        st.markdown(f"""
        <div class="metric-card">
            <h3>🚀 Overall Growth</h3>
            <h2 style="color: {UPI_COLORS['primary']};">{yoy_growth*100:.0f}×</h2>
            <p>Volume increase since launch</p>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        # P2M Share
        p2m_data = p2p_p2m[p2p_p2m['Date'].dt.year >= 2023]
        latest_p2m = p2m_data['P2M_Vol_Share_Pct'].iloc[-1] if not p2m_data.empty else 60
        st.markdown(f"""
        <div class="metric-card">
            <h3>🛍️ P2M Share</h3>
            <h2 style="color: {UPI_COLORS['primary']};">{latest_p2m:.1f}%</h2>
            <p>Merchant payments of total</p>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        # User Base
        latest_users = annual['Active_Users_Millions'].iloc[-1] if not annual.empty else 420
        st.markdown(f"""
        <div class="metric-card">
            <h3>👥 Active Users</h3>
            <h2 style="color: {UPI_COLORS['primary']};">{latest_users:.0f}M+</h2>
            <p>Monthly active users</p>
        </div>
        """, unsafe_allow_html=True)

    # Trend Charts
    st.subheader("📈 Key Metrics Over Time")

    tab1, tab2 = st.tabs(["Volume Trend", "Value Trend"])

    with tab1:
        fig1 = px.line(filtered_monthly, x='Date', y='Volume_Millions',
                       title="Transaction Volume Growth",
                       labels={'Volume_Millions': 'Volume (Millions)', 'Date': 'Year'},
                       color_discrete_sequence=[UPI_COLORS['gradient_1']])
        fig1.update_layout(height=400, hovermode='x unified')
        st.plotly_chart(fig1, use_container_width=True)

    with tab2:
        fig2 = px.area(filtered_monthly, x='Date', y='Value_Crore_INR',
                       title="Transaction Value Growth",
                       labels={'Value_Crore_INR': 'Value (₹ Crore)', 'Date': 'Year'},
                       color_discrete_sequence=[UPI_COLORS['accent']])
        fig2.update_layout(height=400)
        st.plotly_chart(fig2, use_container_width=True)

    # Milestones
    st.subheader("🏆 UPI Milestones")
    milestones = [
        "🎯 2016: UPI Launch with 21 banks",
        "🎯 2019: 1 Billion monthly transactions",
        "🎯 2021: ₹5 Lakh Crore monthly value",
        "🎯 2023: 10 Billion monthly transactions",
        "🎯 2025: ₹20 Lakh Crore monthly value"
    ]
    for milestone in milestones:
        st.markdown(f"✅ {milestone}")

# GROWTH ANALYTICS PAGE
elif selected_page == "📊 Growth Analytics":
    st.header("📊 Growth Analytics Dashboard")

    # Monthly vs YoY Growth
    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.bar(filtered_monthly, x='Date', y='Volume_Millions',
                      title="Monthly Transaction Volume",
                      color='Volume_Millions',
                      color_continuous_scale='Blues')
        fig1.update_layout(height=400)
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        fig2 = px.line(filtered_monthly, x='Date', y='Volume_YoY_Growth_Pct',
                       title="Year-over-Year Growth (%)",
                       color_discrete_sequence=[UPI_COLORS['secondary']])
        fig2.add_hline(y=100, line_dash="dash", line_color="green",
                       annotation_text="100% Growth")
        fig2.update_layout(height=400)
        st.plotly_chart(fig2, use_container_width=True)

    # Seasonal Analysis
    st.subheader("📅 Seasonal Patterns")

    # Monthly seasonality
    seasonal = filtered_monthly.groupby('Month_Name')['Volume_Millions'].mean().reset_index()
    month_order = ['January', 'February', 'March', 'April', 'May', 'June',
                   'July', 'August', 'September', 'October', 'November', 'December']
    seasonal['Month_Name'] = pd.Categorical(seasonal['Month_Name'], categories=month_order, ordered=True)
    seasonal = seasonal.sort_values('Month_Name')

    fig3 = px.bar(seasonal, x='Month_Name', y='Volume_Millions',
                  title="Average Monthly Volume by Month (Seasonality)",
                  labels={'Volume_Millions': 'Avg Volume (Millions)', 'Month_Name': 'Month'},
                  color='Volume_Millions',
                  color_continuous_scale='Viridis')
    st.plotly_chart(fig3, use_container_width=True)

    # Annual Summary Table
    st.subheader("📊 Annual Performance Summary")
    st.dataframe(annual.style.background_gradient(cmap='Blues'), use_container_width=True)

# P2P VS P2M PAGE
elif selected_page == "🔄 P2P vs P2M":
    st.header("🔄 Person-to-Person vs Person-to-Merchant Analysis")

    col1, col2 = st.columns(2)

    with col1:
        # P2P vs P2M Volume
        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(x=p2p_p2m['Date'], y=p2p_p2m['P2P_Volume_Millions'],
                                  name='P2P', fill='tonexty',
                                  line=dict(color=UPI_COLORS['primary'])))
        fig1.add_trace(go.Scatter(x=p2p_p2m['Date'], y=p2p_p2m['P2M_Volume_Millions'],
                                  name='P2M', fill='tonexty',
                                  line=dict(color=UPI_COLORS['accent'])))
        fig1.update_layout(title="P2P vs P2M Volume Split", height=450)
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        # P2M Share Trend
        fig2 = px.area(p2p_p2m, x='Date', y='P2M_Vol_Share_Pct',
                       title="P2M Share of Total Volume (%)",
                       color_discrete_sequence=[UPI_COLORS['secondary']])
        fig2.add_hline(y=50, line_dash="dash", line_color="red",
                       annotation_text="50% Milestone")
        fig2.add_hline(y=60, line_dash="dash", line_color="green",
                       annotation_text="60% Milestone")
        fig2.update_layout(height=450)
        st.plotly_chart(fig2, use_container_width=True)

    # Value Split
    st.subheader("💰 Value Distribution")
    fig3 = px.bar(p2p_p2m.tail(12), x='Date', y=['P2P_Value_Crore', 'P2M_Value_Crore'],
                  title="Transaction Value Split (Last 12 Months)",
                  labels={'value': 'Value (₹ Crore)', 'variable': 'Type'},
                  barmode='group',
                  color_discrete_map={'P2P_Value_Crore': UPI_COLORS['primary'],
                                     'P2M_Value_Crore': UPI_COLORS['accent']})
    st.plotly_chart(fig3, use_container_width=True)

# APP MARKET SHARE PAGE
elif selected_page == "📱 App Market Share":
    st.header("📱 UPI App Market Share Evolution")

    app_share['Period'] = app_share['Year'].astype(str) + " Q" + app_share['Quarter'].astype(str)

    # Area chart
    fig1 = px.area(app_share, x='Period', y=['PhonePe_Pct', 'GooglePay_Pct', 'Paytm_Pct', 'Others_Pct'],
                   title="App Market Share Trend (2018-2025)",
                   labels={'value': 'Market Share (%)', 'variable': 'App'},
                   color_discrete_map={
                       'PhonePe_Pct': '#FF6B6B',
                       'GooglePay_Pct': '#4ECDC4',
                       'Paytm_Pct': '#45B7D1',
                       'Others_Pct': '#96CEB4'
                   })
    fig1.update_layout(xaxis_tickangle=-45, height=500)
    st.plotly_chart(fig1, use_container_width=True)

    # Latest quarter pie chart
    col1, col2 = st.columns(2)

    with col1:
        latest_share = app_share.iloc[-1]
        pie_data = pd.DataFrame({
            'App': ['PhonePe', 'Google Pay', 'Paytm', 'Others'],
            'Share': [latest_share['PhonePe_Pct'], latest_share['GooglePay_Pct'],
                      latest_share['Paytm_Pct'], latest_share['Others_Pct']]
        })
        fig2 = px.pie(pie_data, values='Share', names='App',
                      title=f"Q{latest_share['Quarter']} {int(latest_share['Year'])} Market Share",
                      color_discrete_sequence=[UPI_COLORS['secondary'], UPI_COLORS['primary'],
                                               UPI_COLORS['accent'], '#96CEB4'])
        st.plotly_chart(fig2, use_container_width=True)

    with col2:
        # Market concentration
        hhi = (latest_share['PhonePe_Pct']**2 + latest_share['GooglePay_Pct']**2 +
               latest_share['Paytm_Pct']**2 + latest_share['Others_Pct']**2) / 10000
        st.markdown(f"""
        <div class="metric-card">
            <h3>📊 Market Concentration</h3>
            <h2 style="color: {UPI_COLORS['primary']};">{hhi:.3f}</h2>
            <p>Herfindahl-Hirschman Index (HHI)</p>
            <small>Higher value = more concentrated market</small>
        </div>
        """, unsafe_allow_html=True)

# STATE INSIGHTS PAGE
elif selected_page == "🗺️ State Insights":
    st.header("🗺️ State-wise UPI Adoption Analysis")

    state_clean = state_wise.dropna(subset=['State', 'Volume_Billions_FY25'])

    col1, col2 = st.columns(2)

    with col1:
        # Top states by volume
        top_states = state_clean.nlargest(10, 'Volume_Billions_FY25')
        fig1 = px.bar(top_states, y='State', x='Volume_Billions_FY25',
                      orientation='h', title="Top 10 States by Transaction Volume",
                      labels={'Volume_Billions_FY25': 'Volume (Billions)', 'State': ''},
                      color='Volume_Billions_FY25',
                      color_continuous_scale='Viridis')
        fig1.update_layout(height=500)
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        # Per capita transactions
        fig2 = px.bar(top_states, y='State', x='Per_Capita_Txns_FY25',
                      orientation='h', title="Transactions Per Capita",
                      labels={'Per_Capita_Txns_FY25': 'Transactions Per Person', 'State': ''},
                      color='Per_Capita_Txns_FY25',
                      color_continuous_scale='Plasma')
        fig2.update_layout(height=500)
        st.plotly_chart(fig2, use_container_width=True)

    # Tier analysis
    st.subheader("🏙️ Adoption by City Tier")
    tier_summary = state_clean.groupby('Tier').agg({
        'Volume_Billions_FY25': 'sum',
        'Per_Capita_Txns_FY25': 'mean'
    }).reset_index()

    fig3 = px.bar(tier_summary, x='Tier', y='Volume_Billions_FY25',
                  title="Total Volume by City Tier",
                  color='Volume_Billions_FY25',
                  color_continuous_scale='Blues')
    st.plotly_chart(fig3, use_container_width=True)

# MERCHANT ANALYSIS PAGE
elif selected_page == "🛒 Merchant Analysis":
    st.header("🛒 Merchant Category Analysis")

    top_merchants = merchant.nlargest(10, 'Value_Crore')

    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.bar(top_merchants, y='Category', x='Value_Crore',
                      orientation='h', title="Top 10 Categories by Value",
                      labels={'Value_Crore': 'Value (₹ Crore)', 'Category': ''},
                      color='Value_Crore',
                      color_continuous_scale='Reds',
                      text='Value_Crore')
        fig1.update_traces(texttemplate='%{text:.0f}', textposition='outside')
        fig1.update_layout(height=500)
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        fig2 = px.bar(top_merchants, y='Category', x='Avg_Ticket_INR',
                      orientation='h', title="Average Ticket Size by Category",
                      labels={'Avg_Ticket_INR': 'Average Ticket (₹)', 'Category': ''},
                      color='Avg_Ticket_INR',
                      color_continuous_scale='Greens',
                      text='Avg_Ticket_INR')
        fig2.update_traces(texttemplate='%{text:.0f}', textposition='outside')
        fig2.update_layout(height=500)
        st.plotly_chart(fig2, use_container_width=True)

    # Volume vs Value Scatter
    st.subheader("📊 Category Performance Matrix")
    fig3 = px.scatter(merchant, x='Volume_Millions', y='Value_Crore',
                      size='Avg_Ticket_INR', color='Category',
                      title="Volume vs Value by Merchant Category",
                      labels={'Volume_Millions': 'Volume (Millions)',
                              'Value_Crore': 'Value (₹ Crore)'},
                      hover_data=['Category'])
    fig3.update_layout(height=500)
    st.plotly_chart(fig3, use_container_width=True)

# SECURITY DASHBOARD PAGE
elif selected_page == "🔒 Security Dashboard":
    st.header("🔒 UPI Security & Fraud Analysis")

    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.bar(fraud, x='Financial_Year', y='Fraud_Cases',
                      title="Fraud Cases by Financial Year",
                      labels={'Fraud_Cases': 'Number of Fraud Cases'},
                      color='Fraud_Cases',
                      color_continuous_scale='Reds')
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        fig2 = px.line(fraud, x='Financial_Year', y='Fraud_Rate_Pct',
                       title="Fraud Rate (% of Total Transactions)",
                       labels={'Fraud_Rate_Pct': 'Fraud Rate (%)'},
                       markers=True,
                       color_discrete_sequence=[UPI_COLORS['warning']])
        fig2.add_hline(y=0.001, line_dash="dash", line_color="green",
                       annotation_text="Industry Standard")
        st.plotly_chart(fig2, use_container_width=True)

    # ODR Resolution Rate
    st.subheader("✅ ODR Resolution Rate Trend")
    fig3 = px.bar(fraud, x='Financial_Year', y='ODR_Resolution_Rate_Pct',
                  title="Online Dispute Resolution Success Rate",
                  labels={'ODR_Resolution_Rate_Pct': 'Resolution Rate (%)'},
                  color='ODR_Resolution_Rate_Pct',
                  color_continuous_scale='Greens',
                  text='ODR_Resolution_Rate_Pct')
    fig3.update_traces(texttemplate='%{text:.0f}%', textposition='outside')
    st.plotly_chart(fig3, use_container_width=True)

    # Fraud per transaction
    st.subheader("💰 Fraud Amount Analysis")
    fig4 = px.line(fraud, x='Financial_Year', y='Fraud_Amount_Per_Case_INR',
                   title="Average Fraud Amount per Case",
                   labels={'Fraud_Amount_Per_Case_INR': 'Amount per Case (₹)'},
                   markers=True,
                   color_discrete_sequence=[UPI_COLORS['danger']])
    st.plotly_chart(fig4, use_container_width=True)

# DEMOGRAPHICS PAGE
elif selected_page == "👥 Demographics":
    st.header("👥 Age-wise UPI Adoption Analysis")

    # Adoption trend by age
    fig1 = go.Figure()
    fig1.add_trace(go.Bar(x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2025'],
                          name='2025', marker_color=UPI_COLORS['accent']))
    fig1.add_trace(go.Bar(x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2022'],
                          name='2022', marker_color=UPI_COLORS['primary']))
    fig1.add_trace(go.Bar(x=demographics['Age_Group'], y=demographics['UPI_Adoption_Pct_2019'],
                          name='2019', marker_color=UPI_COLORS['secondary']))
    fig1.update_layout(title="UPI Adoption Rate by Age Group (2019 → 2025)",
                       xaxis_title="Age Group", yaxis_title="Adoption Rate (%)",
                       barmode='group', height=500)
    st.plotly_chart(fig1, use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        # Daily transactions by age
        fig2 = px.bar(demographics, x='Age_Group', y='Avg_Daily_Txns',
                      title="Average Daily UPI Transactions",
                      labels={'Avg_Daily_Txns': 'Daily Transactions'},
                      color='Avg_Daily_Txns',
                      color_continuous_scale='Blues')
        st.plotly_chart(fig2, use_container_width=True)

    with col2:
        # Trust score by age
        fig3 = px.line(demographics, x='Age_Group', y='Trust_Score_Pct',
                       title="Trust Score by Age Group (%)",
                       labels={'Trust_Score_Pct': 'Trust Score (%)'},
                       markers=True,
                       color_discrete_sequence=[UPI_COLORS['info']])
        fig3.add_hline(y=80, line_dash="dash", line_color="green",
                       annotation_text="High Trust Threshold")
        st.plotly_chart(fig3, use_container_width=True)

# GLOBAL BENCHMARK PAGE
elif selected_page == "🌍 Global Benchmark":
    st.header("🌍 India vs Global Real-Time Payment Systems")

    col1, col2 = st.columns(2)

    with col1:
        fig1 = px.bar(global_comp, x='Country', y='Annual_Txn_Billions_2023',
                      title="Annual Real-Time Payment Transactions (2023)",
                      labels={'Annual_Txn_Billions_2023': 'Transactions (Billions)'},
                      color='Real_Time_Share_Pct',
                      color_continuous_scale='Viridis',
                      hover_data=['Payment_System', 'Launch_Year'])
        fig1.update_layout(height=500)
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        fig2 = px.bar(global_comp, x='Country', y='Real_Time_Share_Pct',
                      title="Real-Time Payment Share (%)",
                      labels={'Real_Time_Share_Pct': 'Real-Time Share (%)'},
                      color='Launch_Year',
                      color_continuous_scale='Plasma')
        fig2.update_layout(height=500)
        st.plotly_chart(fig2, use_container_width=True)

    # Comparison table
    st.subheader("📊 Detailed Comparison")
    st.dataframe(global_comp.style.background_gradient(cmap='Blues', subset=['Annual_Txn_Billions_2023', 'Real_Time_Share_Pct']),
                 use_container_width=True)

    # India's position highlight
    india_data = global_comp[global_comp['Country'] == 'India'].iloc[0]
    st.markdown(f"""
    <div style="background: linear-gradient(135deg, {UPI_COLORS['primary']}, {UPI_COLORS['gradient_1']});
                border-radius: 15px; padding: 20px; color: white; margin-top: 20px;">
        <h3 style="color: white;">🇮🇳 India's Leadership Position</h3>
        <ul>
            <li>📊 2nd largest real-time payment market globally</li>
            <li>🚀 84% real-time payment share - highest among major economies</li>
            <li>🏆 Launched UPI in 2016 - now benchmark for digital payments</li>
            <li>📈 Processing more transactions than China, USA, UK combined</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown(f"""
<div style="text-align: center; padding: 20px;">
    <p style="color: {UPI_COLORS['primary']};">
        <strong>Data Sources:</strong> NPCI Official Statistics, RBI Annual Reports, Ministry of Finance
    </p>
    <p style="color: gray; font-size: 12px;">
        Dashboard built with Streamlit & Plotly | Data period: 2016-2025
    </p>
</div>
""", unsafe_allow_html=True)
